// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoQAUr6ilfpxE3Y_KEUfrkmHDwwF77p48',
    appId: '1:541611171280:web:4792084552a16f5a74add5',
    messagingSenderId: '541611171280',
    projectId: 'mb-gate-system',
    authDomain: 'mb-gate-system.firebaseapp.com',
    storageBucket: 'mb-gate-system.appspot.com',
    measurementId: 'G-JJ39YPZVZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxOt3P905MTbCF4ZBgnVf0NjdZQIGkc9k',
    appId: '1:541611171280:android:64181b6f174ea52974add5',
    messagingSenderId: '541611171280',
    projectId: 'mb-gate-system',
    storageBucket: 'mb-gate-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdngu7O_pdscCMI_-YP8C4ZcyW75P-2FA',
    appId: '1:541611171280:ios:2e7cf9b6feeb4f4174add5',
    messagingSenderId: '541611171280',
    projectId: 'mb-gate-system',
    storageBucket: 'mb-gate-system.appspot.com',
    iosClientId: '541611171280-9ggeojmirs81h28v6e6rb37gnpn9j1n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdngu7O_pdscCMI_-YP8C4ZcyW75P-2FA',
    appId: '1:541611171280:ios:2e7cf9b6feeb4f4174add5',
    messagingSenderId: '541611171280',
    projectId: 'mb-gate-system',
    storageBucket: 'mb-gate-system.appspot.com',
    iosClientId: '541611171280-9ggeojmirs81h28v6e6rb37gnpn9j1n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatesystem',
  );
}
